--SELECT first_name,last_name,birth_day from students ;
--SELECT first_name,last_name,birth_day from students ORDER BY last_name ASC LIMIT 4;
--SELECT first_name,last_name,birth_day from students WHERE birth_day > '01/01/2000';
--SELECT * from students  LIMIT 3 OFFSET 2 ;
